# Generated by Django 4.1.7 on 2023-04-02 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('pic', models.ImageField(upload_to='brand')),
            ],
        ),
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.CharField(max_length=15)),
                ('addressline1', models.CharField(max_length=30)),
                ('addressline2', models.CharField(max_length=30)),
                ('addressline3', models.CharField(max_length=30)),
                ('pin', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pic', models.ImageField(upload_to='user')),
            ],
        ),
        migrations.CreateModel(
            name='maincategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=10)),
                ('baseprice', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('finalprice', models.IntegerField()),
                ('stock', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('pic1', models.ImageField(blank=True, default='', null=True, upload_to='product')),
                ('pic2', models.ImageField(blank=True, default='', null=True, upload_to='product')),
                ('pic3', models.ImageField(blank=True, default='', null=True, upload_to='product')),
                ('pic4', models.ImageField(blank=True, default='', null=True, upload_to='product')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.brand')),
                ('maincategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.maincategory')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subcategory')),
            ],
        ),
    ]
