# Generated by Django 4.1.7 on 2023-07-14 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_rename_checkout_checkoutproducts_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='Product',
        ),
    ]
